# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvaluateTeamDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_evaluateTeamDialog(object):
    def setupUi(self, evaluateTeamDialog):
        evaluateTeamDialog.setObjectName("evaluateTeamDialog")
        evaluateTeamDialog.resize(480, 320)
        self.gridLayout_2 = QtWidgets.QGridLayout(evaluateTeamDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.titleLabel = QtWidgets.QLabel(evaluateTeamDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 0, 0, 1, 4)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.selectTeam = QtWidgets.QComboBox(evaluateTeamDialog)
        self.selectTeam.setObjectName("selectTeam")
        self.selectTeam.addItem("")
        self.horizontalLayout1.addWidget(self.selectTeam)
        self.selectMatch = QtWidgets.QComboBox(evaluateTeamDialog)
        self.selectMatch.setObjectName("selectMatch")
        self.selectMatch.addItem("")
        self.horizontalLayout1.addWidget(self.selectMatch)
        self.gridLayout_2.addLayout(self.horizontalLayout1, 1, 0, 1, 4)
        self.line0 = QtWidgets.QFrame(evaluateTeamDialog)
        self.line0.setFrameShape(QtWidgets.QFrame.HLine)
        self.line0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line0.setObjectName("line0")
        self.gridLayout_2.addWidget(self.line0, 2, 0, 2, 4)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.playerList = QtWidgets.QListWidget(evaluateTeamDialog)
        self.playerList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.playerList.setObjectName("playerList")
        self.horizontalLayout2.addWidget(self.playerList)
        self.playerPoints = QtWidgets.QListWidget(evaluateTeamDialog)
        self.playerPoints.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.playerPoints.setObjectName("playerPoints")
        self.horizontalLayout2.addWidget(self.playerPoints)
        self.gridLayout_2.addLayout(self.horizontalLayout2, 5, 0, 1, 4)
        self.pointsLabel = QtWidgets.QLabel(evaluateTeamDialog)
        self.pointsLabel.setObjectName("pointsLabel")
        self.gridLayout_2.addWidget(self.pointsLabel, 4, 2, 1, 1)
        self.scoreLabel = QtWidgets.QLabel(evaluateTeamDialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setText("")
        self.scoreLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scoreLabel.setObjectName("scoreLabel")
        self.gridLayout_2.addWidget(self.scoreLabel, 4, 3, 1, 1)
        self.playersLabel = QtWidgets.QLabel(evaluateTeamDialog)
        self.playersLabel.setObjectName("playersLabel")
        self.gridLayout_2.addWidget(self.playersLabel, 4, 0, 1, 1)
        self.horizontalLayout0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout0.setObjectName("horizontalLayout0")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout0.addItem(spacerItem)
        self.calculateScore = QtWidgets.QPushButton(evaluateTeamDialog)
        self.calculateScore.setObjectName("calculateScore")
        self.horizontalLayout0.addWidget(self.calculateScore)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout0.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout0, 6, 0, 1, 4)

        self.retranslateUi(evaluateTeamDialog)
        QtCore.QMetaObject.connectSlotsByName(evaluateTeamDialog)

    def retranslateUi(self, evaluateTeamDialog):
        _translate = QtCore.QCoreApplication.translate
        evaluateTeamDialog.setWindowTitle(_translate("evaluateTeamDialog", "Evaluate Team"))
        self.titleLabel.setText(_translate("evaluateTeamDialog", "EVALUATE THE PERFORMACE OF YOUR FANTASY TEAM"))
        self.selectTeam.setCurrentText(_translate("evaluateTeamDialog", "Select Team"))
        self.selectTeam.setItemText(0, _translate("evaluateTeamDialog", "Select Team"))
        self.selectMatch.setItemText(0, _translate("evaluateTeamDialog", "Select Match"))
        self.pointsLabel.setText(_translate("evaluateTeamDialog", "POINTS:"))
        self.playersLabel.setText(_translate("evaluateTeamDialog", "PLAYERS"))
        self.calculateScore.setText(_translate("evaluateTeamDialog", "CALCULATE SCORE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    evaluateTeamDialog = QtWidgets.QDialog()
    ui = Ui_evaluateTeamDialog()
    ui.setupUi(evaluateTeamDialog)
    evaluateTeamDialog.show()
    sys.exit(app.exec_())
