# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewTeamDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newTeamDialog(object):
    def setupUi(self, newTeamDialog):
        newTeamDialog.setObjectName("newTeamDialog")
        newTeamDialog.resize(300, 70)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newTeamDialog.sizePolicy().hasHeightForWidth())
        newTeamDialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(newTeamDialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 9, 75, 52))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.infoLabel = QtWidgets.QLabel(newTeamDialog)
        self.infoLabel.setGeometry(QtCore.QRect(10, 10, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.nameText = QtWidgets.QLineEdit(newTeamDialog)
        self.nameText.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.nameText.setObjectName("nameText")

        self.retranslateUi(newTeamDialog)
        self.buttonBox.accepted.connect(newTeamDialog.accept)
        self.buttonBox.rejected.connect(newTeamDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(newTeamDialog)

    def retranslateUi(self, newTeamDialog):
        _translate = QtCore.QCoreApplication.translate
        newTeamDialog.setWindowTitle(_translate("newTeamDialog", "New Team"))
        self.infoLabel.setText(_translate("newTeamDialog", "Enter Team Name In Provided Space"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newTeamDialog = QtWidgets.QDialog()
    ui = Ui_newTeamDialog()
    ui.setupUi(newTeamDialog)
    newTeamDialog.show()
    sys.exit(app.exec_())
