# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenTeamDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_openTeamDialog(object):
    def setupUi(self, openTeamDialog):
        openTeamDialog.setObjectName("openTeamDialog")
        openTeamDialog.resize(300, 70)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(openTeamDialog.sizePolicy().hasHeightForWidth())
        openTeamDialog.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(openTeamDialog)
        self.buttonBox.setGeometry(QtCore.QRect(220, 9, 75, 52))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.selectTeam = QtWidgets.QComboBox(openTeamDialog)
        self.selectTeam.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.selectTeam.setObjectName("selectTeam")
        self.selectTeam.addItem("")
        self.infoLabel = QtWidgets.QLabel(openTeamDialog)
        self.infoLabel.setGeometry(QtCore.QRect(10, 10, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")

        self.retranslateUi(openTeamDialog)
        self.buttonBox.accepted.connect(openTeamDialog.accept)
        self.buttonBox.rejected.connect(openTeamDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(openTeamDialog)

    def retranslateUi(self, openTeamDialog):
        _translate = QtCore.QCoreApplication.translate
        openTeamDialog.setWindowTitle(_translate("openTeamDialog", "Open Team"))
        self.selectTeam.setItemText(0, _translate("openTeamDialog", "Select Team"))
        self.infoLabel.setText(_translate("openTeamDialog", "Select Team From Dropdown List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    openTeamDialog = QtWidgets.QDialog()
    ui = Ui_openTeamDialog()
    ui.setupUi(openTeamDialog)
    openTeamDialog.show()
    sys.exit(app.exec_())
